// import React from 'react'
// import './index.css'
// import c1_1 from '../../assets/images/c1-1.png'

// export default function ThesisClassic() {
//   return (
//     <div className="ThesisClassic-container">
//       <div className='ThesisClassic'>
//         <div className="ThesisClassic-head">Proceedings of the 35th Chinese Control Conference<br/>July 27-29, 2016, Chengdu, China</div>
//         <h1 className="ThesisClassic-title">Feedback-based platoon control for connected autonomous vehicles under different communication network topologies</h1>
//         <div className="ThesisClassic-author">LI Yongfu<sup>1</sup> ,LI Kezhi<sup>1</sup> ,CAI Linqin<sup>1</sup>, ZHU Hao<sup>1</sup>, SUN Fenglan<sup>2</sup></div>
//         <div className="ThesisClassic-contact-details">1. Chongqing Collaborative Innovation Center for Information Communication Technology, College of Automation, Chongqing<br/>University of Posts and Telecommunications, Chongqing 400065, China.<br/>E-mail: <a>laf1212@163.com</a><br/>2. Research Center of System Theory and Application, Chongqing University of Posts and Telecommunications, Chongqing 400065, China</div>
//         <div className="ThesisClassic-abstract"><strong>Abstract:</strong> This study proposes a feedback-based platoon control protocol for connected autonomous vehicles (CAVs) under different communication network topologies. In particular, the graph theory is used to describe the communication network topologies among CAVs. Subsequently, the feedback-based protocol is proposed to control the vehicular platoon. In addition, the stability and consensus of the proposed protocol are analyzed using the Lyapunov technique and the LaSalle’s invariance principle. Effects of different communication network topologies on convergence and robustness of platoon control are investigated. Results from numerical experiments demonstrate the effectiveness of the proposed protocol with respect to the position and velocity consensus in terms of the convergence time and robustness. </div>
//         <div className="ThesisClassic-key"><strong>Key Words:</strong> Connected autonomous vehicle; platoon control; communication network topologies; consensus </div>
//         {/* <div className="ThesisClassic-content">
//           <h3 className="ThesisClassic-introduction-title"><strong>1&nbsp;&nbsp;Introduction</strong></h3>
//           <div className="ThesisClassic-introduction">
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;Platoon-based driving pattern (a special vehicular formation) referred to a group of vehicles traveling together with short inter-vehicle headway is regarded as a promising driving manner <a>[1-4]</a>. Recently, autonomous vehicles (AVs), i.e., Google driverless car, have received much attention. Compared to human-driven vehicles, AVs can be operated without direct driver input to control the steering, acceleration, and braking so that the vehicles can travel with higher mobility, less faults, and smarter choices <a>[5-6]</a>. In this context, AVs equipped with the communication technology, connected autonomous vehicles (CAVs), can generate and capture environmentally relevant real-time transportation data and use this data to create actionable information to support and facilitate green transportation choices <a>[7]</a>, such as improve the efficiency of intersections <a>[8]</a>, and apply to the real-time adaptive signal control <a>[9]</a>. On the other hand, in many developing countries where lanes may not be clearly demarcated on a road though multiple vehicles can travel in parallel with later gaps. And past studies illustrate that the vehicles travel with lateral gaps consume more energy under non-lane-discipline environment <a>[10]</a>. Hence, in the context of CAVs, there is a research need to study how the CAVs in a road to form a vehicular platoon considering the longitudinal and lateral gaps simultaneously. </p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;The objective of platoon control is to ensure that all vehicles in a platoon move at the same speed while maintaining a desired formation geometry, which is specified by a desired inter-vehicle spacing policy <a>[11]</a>. Practically, many approaches to solve formation control problem have been proposed, which mainly include leader-follower, virtual leader, etc. The leader-follower approach is of significance for the multi-agent control problem, in which the leader is a particular agent whose motion is independent of all others and followed by all the others <a>[12-14]</a>. Wang and Wu <a>[15]</a> studied the formation control problem of leader-follower system with different topologies. Wang et al. <a>[16]</a> proposed a method for coordinated control using the integrated network consensus, and analyzed the performance with respect to the robustness, anti-interference, and noise rejection. By applying the local leader-follower control to small fraction of agents, Guan et al. <a>[17]</a> proved that the states of the pinning-controlled multi-agent system can approach the states of the leader. In addition, Su et al. <a>[18]</a>, Peng and Yang <a>[19]</a> considered the situation that the leader moves with a varying velocity, and then designed the protocols which enable the followers to asymptotically track the leader. Although the leader-follower approach depends heavily on the leader for achieving the goal, it is widely used in the cooperative systems for its simplicity and scalability</p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;The virtual leader approach assumes that each agent behaves like particles embedded in a rigid virtual structure <a>[20]</a>. Ren <a>[21]</a> proposed a feedback protocol in order to improve the performance of the system in terms of the robustness. Shi et al. <a>[22]</a> proposed a set of coordination control laws that enables the group to generate the desired stable state, and then studied the coordinated control for multiple agents using the virtual leader approach. Lu et al. <a>[23]</a> investigated the tracking control problems with a virtual leader under fixed and switching topologies, respectively. Zhang et al. <a>[24]</a> proposed a distributed feedback law related to the virtual leader to address the issue of coordinated path tracking. This approach can avoid the problem of disturbance inherent in the leader–follower approach, but it needs the high cost of communication and the computation capabilities to synthesize the virtual leader and communicate its position in time to support real-time control of other vehicles <a>[25-26]</a>.</p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;However, the above mentioned studies do not consider the effects of communication network topologies on vehicular platoon control. Also, they do not consider the space constraints. Hence, motivated by the CAVs context, the focus of this study is on the protocol design in order to facilitate the CAVs on a road to form a platoon formation under different communication network topologies. The emphasis is to investigate the effects of communication network topologies with respect to the convergence and robustness. Specifically, we describe the communication network topology of CAVs using the algebraic graph theory. In addition, feedback-based protocol is designed to control the platoon considering the longitudinal and lateral gaps simultaneously. The stability and consensus of the proposed protocol are analyzed using the Lyapunov technique and the LaSalle’s invariance principle. Moreover, the effects of the different communication network topologies of CAVs on convergence and robustness are investigated. Results from numerical experiments demonstrate the effectiveness of the proposed protocol with respect to the position and velocity consensus in terms of the convergence time and robustness</p>
//             <p className='ThesisClassic-diviLine'></p>
//             <p className="ThesisClassic-note"> &nbsp;&nbsp;&nbsp;&nbsp;*  This work is supported by National Nature Science Foundation under Grant 61304197 and 61503053, the Scientific and Technological Talents of Chongqing under Grant cstc2014kjrc-qnrc30002, the Key Project of Application and Development of Chongqing under Grant cstc2014yykfB40001, “151” Science and Technology Major Project of Chongqing-General Design and Innovative Capability of Full Information Based Traffic Guidance and Control System (grant no.cstc2013jcsf-zdzxqqX0003). </p>
//           </div>
//           <h3 className="ThesisClassic-fromAndPre-title"><strong>2&nbsp;&nbsp;Formulation and preliminaries</strong></h3>
//           <div className="ThesisClassic-formAndPre">
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;As the example shown in Fig. 1, AVs travel in parallel with lateral gaps on a road. The leading vehicle (noted as the leader) serves as a reference, where <em>x</em><sub>L</sub>(0) denotes the initial position, and <em>v</em><sub>L</sub>(0) represents the desired speed for all other followers (noted as vehicles <em>i</em> , <em>i</em> + 1, <em>i</em> - 2 ) in the platoon to follow. Considering the characteristics of AVs, we treat each AV as an agent using the multi-agent system theory. The purpose of this study is to design control protocols to facilitate AVs in Fig. 1 to form a platoon formation as shown in Fig. 2 under connected environments.  </p>
//             <div className='ThesisClassic-img'><img src={c1_1} alt="c1_1" width={`30%`}/></div>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;The information exchange among CAVs can be described by undirected graph. Each vertex represents an individual CAV and each edge represents an active communication link. The detailed description can be defined as follow <a>[12, 27-28]</a>: </p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;Let <em>G</em> = {`{`}<em>V,E,A</em>{`}`} be a weighted graph of order <em>n</em> , where <em>V</em> = {`{`}<em>v<sub>1</sub>,v<sub>2</sub>,...,v<sub>3</sub></em>{`}`} is the set of n nodes with indexes belonging to a finite index set <em>I</em> = {`{`}<em>1,2, ...,n</em> {`}`} ! , <em>E</em> &sube; <em>V</em> x <em>V</em> is the set of edges, whose elements denote the communication links between the vehicles. <em>A</em> = [<em>a<sub>ij</sub></em>] is the adjacency matrix of the weighted graph <em>G</em> with nonnegative adjacency elements <em>a<sub>ij</sub></em> &ge; 0,&forall;<em>i,j</em> &isin; <em>I</em> . If there is an edge between agent i and agent j , then <em>a<sub>ij</sub></em> = <em>a<sub>ij</sub></em> &gt; 0 , otherwise <em>a<sub>ij</sub></em> = 0 . And let <strong><em>1</em></strong> denote the <em>n</em> x <em>1</em> column vector of all ones. <em>R<sup>n</sup></em> denotes the set of n-dimensional real column vectors. We consider another graph <em>G</em> associated with the system consisting of n agents (followers) and one leader. Let the linked matrix be <em>K</em> = <em>diag(k<sub>1</sub>,k<sub>2</sub>,...k<sub>n</sub>)</em>, if follower <em>i</em> connects with the leader, then <em>k<sub>i</sub></em> &gt; 0, otherwise <em>k<sub>i</sub></em> = 0. If a graph <em>G</em> with &forall;(<em>i, j</em>) &isin; <em>E</em> =&gt; (<em>j, i</em>) &isin; <em>E</em>, we say that graph <em>G</em> is an undirected graph. Then the leader node is said to be globally reachable in <em>G</em> , if there is a path from every other node to leader in <em>G</em> .The edges of undirected graph denote that the communications between vehicle are mutual. In this study, we consider the followers network topologies under the undirected graph. </p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;Following the leader-follower approach, we consider the followers of the system as <a>[29]</a>:<br/> where i xt R2 ( )  and i vt R2 ( )  are the position and velocity of vehicle i . i ut R2 ( )  is the control input. </p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;The leader of the system is described as <a>[29]</a>:<br/> where 2 ( ) L xt R and 2 ( ) L vt R are the position and svelocity of the leader. 2 ( ) L ut R is the control input of the sleader. </p>
//           </div>
//           <h3 className='ThesisClassic-ctrlProtDesign-title'><strong>3&nbsp;&nbsp;Control protocol design</strong></h3>
//           <div className="ThesisClassic-ctrlProtDesign">
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;To address the scenario as shown in Fig. 1, we propose the feedback-based control protocol as follows: <br/>where ij a is adjacency weight between vehicle i and vehicle j ; ij ji r r   is the vector of position, which represent desired gaps between vehicle i and vehicle j ; x y i ii r rr T  (, ) , , x y i i r r is the desired longitudinal gap and lateral gap; the linked weight 0 i k  if vehicle i receive information from leader and 0 otherwise. C and H are the gain parameters of system</p>
//             <p>&nbsp;&nbsp;&nbsp;&nbsp;Following the approach proposed by Ren in [12], we define the position error and velocity error as ( ) ( ) ( )d ii L i xt xt v r   U U ¨  t 0 1 , and () () () ii L vt vt v t   1 , respectively, where ( ) i x t  , ( ) i v t  both possess two vectors in horizontal and vertical coordinates. Such as the position error T ( ) [ ( ), ( )] x y i ii xt x t x t    , and the velocity error T ( ) [ ( ), ( )] x y i ii vt v t v t    . And the ( )d L v U U ¨ t 0  is an auxiliary notation for obtaining the error position corresponding to the error velocity. Hence, the error equation can be obtained as follows: <br/>where i n  1,2, , . " We can analyze the stability and consensus of the vehicular platoon based on Eq. (4) according to the following lemma. </p>
//             <div className="ThesisClassic-Lemma">
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;<strong>Lemma 1:</strong>(LaSalle’s Invariance Principle [30]) Let x t( ) be a solution of xt fx () ( ) , 0 (0) n x xR  , where : n fU R o is continuous with an open subset U of n R , and VU R : o be a locally Lipschitz function such that DV xt ( ( )) 0  d , where D denotes the upper Dini derivative. Then 0 ( ) x U  4  is contained in the union of all solutions that remain in S x U DV x ^ ` : () 0   , where 0 ( ) x  4 denotes the positive limit set.  </p>
//             </div>
//             <div className='ThesisClassic-Theorem'>
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;<strong>Theorem 1:</strong>Suppose that the initial position and velocity of each vehicle are given. Assume that under protocol (3) with the feedback gain 1 2 diag( , , ) K kk k  ! n satisfying 0 i k  if vehicle i connects with the leader, otherwise 0 i k  , the states of vehicles can be directly or indirectly affected by the state of the leader vehicle. </p>
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;Then we have: (i)lim 0 x x xx i i Li t x xx r ld    ; lim 0 y y yy i i Li t x xx r ld    ; (ii) lim 0 x xx i iL t v vv of   ; lim 0 y yy i iL t v vv of   . </p>
//             </div>
//             <div className='ThesisClassic-proof'> 
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;<strong>Proof:</strong>For the error dynamic Eq. (4), inspired by the LaSalle’s Invariance Principle [30], the candidate Lyapunov function is defined as [17]:<br/>Considering the time derivative of ( ),( 1,2,3) Vt k k  along the solution of Eq. (4), we can obtain <br/>Consequently, we have <br/>Note that the network topology of the system is undirected. Consequently, it follows from Eq. (7) that <br/>From condition of Theorem 1, we know that parameters , 0 ij i a k p . Then, according to Eq. (9), we can obtain 0 i j v v     , which implies 0 i j v v       . Hence, we have <br/>Based on Eq. (10), we can obtain that <br/>From Eq. (11), we know 0 i j x x     . According to lemma 1, we have () () 0 i Li xt x t r  l , () () 0 i L vt v t  l for all i I  , as t l d .That means lim i t x ld   () () 0 i Li xt x t r  l and lim ( ) ( ) 0 ii L t v vt v t ld  l  in horizontal and vertical coordinates. So we have lim 0 x x xx i i Li t x xx r ld    , lim y y yy i i Li t x xx r ld     0 , lim 0 x xx i iL t v vv of   , and lim y yy i iL t v vv of    0 . The proof is completed. </p>
//             </div>
//             <h3 className='ThesisClassic-numExp-title'><strong>4&nbsp;&nbspNumerical experiments</strong></h3>
//             <div className="ThesisClassic-numExp">
//               <p>To investigate the effects of communication network topologies on the performance associated with the convergence and robustness, we discuss two scenarios as shown in Fig .3. </p>
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;Fig.3 Different network topologies: (a) Case I; (b) Case II; For comparison purpose, we give the same simulation conditions as follows: </p>
//               <p>(i)Gain parameters: we set C H   1 ; </p>
//               <p>(ii)The initial states and desired distance of each vehicle are presented as in Table 1. </p>
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;Fig. 6 The velocity trajectories: (a) x-velocity; (b) y-velocity.<br/><strong>Case I:</strong>In this scenario, each the follower AV, i.e., AVs, i, i+1, and i+2, communicate with the others via V2V communication under the connected environment. The leader can send its relevant information, i.e., position and velocity, to its neighboring AVs, i.e., AVs, i+1, and i+2. The communication network topology is shown in Fig. 3a. To address this scenario, we adopt the proposed control protocol as shown in Eq. (3). Fig. 4 shows the position trajectories in two-dimensional plane. From Fig. 4, the leader keep the moving direction and the followers gradually track the leader. Specifically, the longitudinal gaps between the followers and leader converge to the desired distance as shown in Fig. 5(a), while the corresponding lateral gaps converge to zero as shown in Fig. 5(b). In addition, from Fig. 5, we know that the convergence time of longitudinal and later gaps is 7.9s and 9.2s, respectively. Fig. 6 shows the velocity trajectories. Fig. 6(a) shows that the velocities of followers in x-coordinate can converge to the desired velocity (the leader’s velocity) and keep moving constantly. Fig. 6(b) shows that the velocities of followers in y-coordinate can converge to zero. Also, the convergence time of x-coordinate and y-coordinate is 7.9s and 9.2s, respectively. Hence, Fig. 6 shows that the velocity of CAVs can reach a consensus state. Therefore, according to Figs. 4, 5, and 6, the CAVs can form a platoon formation with the designed control protocol. </p>
//               <p><strong>Case II:</strong>This section provides a comparison under different communication network topologies. In practice, the topology between CAVs may be changed due to the disturbances and the communication range limitations.</p>
//               <p>To investigate the effects of different communication network topologies on formation control, we consider the scenario as shown in Fig. 3b. In this scenario, we assume the links between the AVs i and i+1, and AVs i and i+2, fail due to the disturbance. AVs i+1 and i+2 can communicate with each other. Similar to the case I, we also adopt the proposed control protocol as shown in Eq. (3). Fig. 7 shows the position trajectories in two-dimensional plane. From Fig. 7, the leader keeps its moving direction and the followers gradually track the leader except AV i. Specifically, the longitudinal gaps between the followers and leader converge to the desired distance as shown in Fig. 8(a), while the corresponding lateral gaps converge to zero as shown in Fig. 8(b). In addition, Fig. 8 shows that the convergence time of longitudinal and later gaps is 6.5s and 7.4s, respectively. Fig. 9(a) shows that the velocities of followers in x-coordinate can converge to the desired velocity (the leader’s velocity) and keep maintaining a constant velocity. Fig. 9(b) shows that the velocities of followers in y-coordinate can converge to zero. Also, the convergence time of x-coordinate and y-coordinate is 6.5s and 7.4s, respectively. In addition, the oscillation patterns are similar in these two scenarios. In addition, Figs. 7 and 8 show that AV i cannot join in the platoon. This is because the communication links between AV i and its neighboring AVs, i.e., AVs i+1 and i+2, fail due to the disturbance. Hence the proposed control protocol fails to control AV i via the information from its neighbors. Note that this study deals with forming an AV platoon with a fully connected communication network. For the case with disconnected communication network, the disconnected AVs can be controlled by the other control protocols that are out of the scope of this study. </p>
//               <p>&nbsp;&nbsp;&nbsp;&nbsp;Fig. 9 The velocity trajectories: (a) x-velocity; (b) y-velocity. Table 2 summarizes the performance of the proposed control protocols with different communication network topologies. Based on the above discussion, we conclude that: (i) The proposed control protocols can facilitate AVs on a road to form a platoon formation under the connected environment; (ii) The position and velocity trajectories of CAVs can achieve the consensus state; (iii) The complexity of the network topology decrease, the impact between vehicles is smaller and the convergence time is reduced. And the robustness of the CAV system can be guaranteed under different communication network topologies. </p>
//             </div>
//             <h3 className="ThesisClassic-Conclusion-title"><strong>5&nbsp;&nbsp;Conclusion</strong></h3>
//             <div className="ThesisClassic-Conclusion">
//               <p>A feedback-based protocol is designed to control CAV vehicular platoon under different communication network topologies. Stability and consensus of the proposed protocol is analyzed using the Lyapunov technique. Theoretical analysis proves that the longitudinal and lateral gaps as well as the velocity can be simultaneously reach the consensus state. In addition, the effects of different communication network topologies are also analyzed. Results from numerical experiments verify the effectiveness of the proposed control protocol with respect to the position and velocity in terms of the convergence time and robustness</p>
//             </div>
//             <h3 className='ThesisClassic-reference-title'><strong>References</strong></h3>
//             <div className="ThesisClassic-reference">
//                 <p>[1]&nbsp;&nbsp;B. Van Arem, CJG. Vanel, R. Visser, The impact of cooperative adaptive cruise control on traffic-flow characteristics, IEEE Trans. Intell. Transp. Syst., 2006, 7(4): 429-436.
//                 <br/>[2]&nbsp;&nbsp;S. Li, L. Yang, Z. Gao, Coordinated cruise control for high-speed train movements based on a multi-agent model, Transp. Res. Part C, 2015, 56: 281-292. 
//                 <br/>[3]&nbsp;&nbsp;D. Jia, K. Lu, J. Wang, On the network connectivity of platoon-based vehicular cyber-physical systems, Transp. Res. Part C , 2014, 40(1): 215-230.
//                 <br/>[4]&nbsp;&nbsp;R. Horowitz, P. Varaiya, Control design of an automated highway system. Proceedings of the IEEE, 2000, 88(7): 913-925.
//                 <br/>[5]&nbsp;&nbsp;Y. Shiomi, T. Yoshii, R. Kitamura, Platoon-based traffic flow model for estimating breakdown probability at single-lane expressway bottlenecks, Procedia-Social and Behavioral Sciences, 2011, 17(9): 591-610.
//                 <br/>[6]&nbsp;&nbsp;K. Liang, Coordination and routing for fuel-efficient heavy-duty vehicle platoon formation, Licentiate Thesis, Sweden, 2014. 
//                 <br/>[7]&nbsp;&nbsp;Y. Zhang, G. Cao, V-PADA: vehicle-platoon-aware data access in VANETs, IEEE Trans. Veh. Technol. 2011, 60(5): 2326-2339.
//                 <br/>[8]&nbsp;&nbsp;S. Guler, M. Menendez, L. Meier, Using connected vehicle technology to improve the efficiency of intersections, Transp. Res. Part C , 2014, 46(46): 121-131.
//                 <br/>[9]&nbsp;&nbsp;Y. Feng, K. Head, S. Khoshmagham, M. Zamanipour, A real-time adaptive signal control in a connected vehicle environment, Transp. Res. Part C, 2015, 55: 460-473.
//                 <br/>[10]&nbsp;&nbsp;J. Laval, C. Toth, Y. Zhou, A parsimonious model for the formation of oscillations in car-following models, Transp. Res. Part B, 2014, 70:228-238.
//                 <br/>[11]&nbsp;&nbsp;Y. Zheng, S. Li, J. Wang, L. Wang, Influence of information flow topology on closed-loop stability of vehicle platoon with rigid formation, IEEE International Conference on Intelligent Transportation Systems, 2014: 2094-2100.
//                 <br/>[12]&nbsp;&nbsp;W. Ren, Consensus based formation control strategies for multi-vehicle systems, IEEE Conference on American Control, 2006:4237-4242
//                 <br/>[13]&nbsp;&nbsp;Y. Hong, G. Chen, L. Bushnell, Distributed observers design for leader-following control of multi-agent networks, Automatica, 2008, 44(3): 846-850.
//                 <br/>[14]&nbsp;&nbsp;S. Djaidja, Q.Wu, Stochastic consensus of leader-following multi-agent systems under additive measurement noises and time-delays, European Journal of Control, 2015, 23: 55-61.
//                 <br/>[15]&nbsp;&nbsp;J. Wang, H. Wu, Leader-following formation control of multi-agent systems under fixed and switching topologies, International Journal of Control, 2012, 85(6): 695-705. 
//                 <br/>[16]&nbsp;&nbsp;L. Wang, A. Syed, G. Yin, A. Pandya, H. Zhang, Control of vehicle platoons for highway safety and efficient utility. Consensus with communications and vehicle dynamics, J. Syst. Sci. Complex. 2014, 27(4): 605-631. 
//                 <br/>[17]&nbsp;&nbsp;Z. Guan, F. Sun, Y. Wang, T. Li, Finite-time consensus for leader-following second-order multi-agent networks, IEEE Trans. Circuits Syst. I, 2012, 59(11): 2646-2654. 
//                 <br/>[18]&nbsp;&nbsp;H. Su, X. Wang, Z. Lin, Flocking of multi-agents with a virtual leader part II: with a virtual leader of varying velocity, the 46th IEEE Conference on Decision and Control, 2007: 1429-1434. 
//                 <br/>[19]&nbsp;&nbsp;K. Peng, Y. Yang, Leader-following consensus problem with a varying-velocity leader and time-varying delays, Physica A, 2009, 388(2): 193-208. 
//                 <br/>[20]&nbsp;&nbsp;X. Li, D. Zhu, Y. Qian, A Survey on formation control algorithms for multi-AUV System, Unmanned Systems, 2014, 2(4): 351-359. 
//                 <br/>[21]&nbsp;&nbsp;W. Ren, Decentralized scheme for spacecraft formation flying via the virtual structure approach, J Guid. Control Dyn., 2004, 27:73-82. 
//                 <br/>[22]&nbsp;&nbsp;H. Shi, L. Wang, T. Chu, Virtual Leader Approach to Coordinated Control of Multiple Mobile Agents with Asymmetric Interactions, IEEE Conference on Decision and Control, European Control, 2005: 51-65.  
//                 <br/>[23]&nbsp;&nbsp;X. Lu, R. Lu, S. Chen, J. Lu, Finite-time distributed tracking control for multi-agent systems with a virtual leader, IEEE Trans. Circuits Syst. I , 2013, 60(2): 352-362. 
//                 <br/>[24]&nbsp;&nbsp;Q. Zhang, L. Lapierre, X. Xiang, Distributed Control of Coordinated Path Tracking for Networked Nonholonomic Mobile Vehicles, IEEE Trans. Ind. Informat., 2013, 9(1): 472-484. 
//                 <br/>[25]&nbsp;&nbsp;Q. Zhang, Z. Yang, J. Liang, Z. Chen, Rendezvous of multi-agents with time delay and virtual leader, IEEE International Conference on Electric Information and Control Engineering, 2011: 1572-1575. 
//                 <br/>[26]&nbsp;&nbsp;W. Wang, H. Peng, Flocking control under virtual leader-follower with communication time-delay, IEEE Conference on Power Engineering and Automation, 2012: 1-4.
//                 <br/>[27]&nbsp;&nbsp;J. Fax, R. Murray, Information flow and cooperative control of vehicle formations, IEEE Trans. Automa. Control, 2004:1465-1476
//                 <br/>[28]&nbsp;&nbsp;X. Luo, N. Han, X. Guan, Leader-following formation control of multi-agent networks based on distributed observers, Chin. Phys. B, 2010, 10: 7-15. 
//                 <br/>[29]&nbsp;&nbsp;Y. Li, K. Li, T. Zheng, X. Hu, H. Feng, Y. Li, Evaluating the performance of vehicular platoon control under different network topologies of initial states, Phys. A, 2016, 450: 359-368. 
//                 <br/>[30]&nbsp;&nbsp;N. Rouche, P. Habets, M. Laloy, Stability theory by Lyapunov's direct method, Stability Theory by Liapunovÿs Direct Method. Springer New York, 1977. </p>
//             </div>
//           </div>
//         </div>
//         <div className="ThesisClassic-license"><strong>Authorized licensed use limited to: Guangdong Univ of Tech. Downloaded on July 11,2022 at 03:01:56 UTC from IEEE Xplore. Restrictions apply</strong></div> */}
//       </div>
//     </div>
//   )
// }

import React from 'react'
import './index.css'

export default function ThesisClassic() {

  // 跳转
  function handleJump(e){
    e.preventDefault();
    // 在react中想要跳转并且打开新页面得这样
    const w=window.open('about:blank');
    w.location.href="http://qgailab.com/paper-static/cav/cav1.pdf"
  }

  return (
    <div className="ThesisClassic-container">
        <div className='ThesisClassic'>
        <div className="ThesisClassic-title">Feedback-based platoon control for connected autonomous vehicles under different communication network topologies</div>
        <div className="ThesisClassic-author">by LI Yongfu ,LI Kezhi ,CAI Linqin, ZHU Hao, SUN Fenglan</div>
        <div className="ThesisClassic-original"><a href='#' onClick={(Event)=>{handleJump(Event)}}>Click to see original&gt;&gt;</a></div>
        <div className="ThesisClassic-abstract-title">Abstract</div>
        <div className="ThesisClassic-abstract">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This study proposes a feedback-based platoon control protocol for connected autonomous vehicles (CAVs) under different communication network topologies. In particular, the graph theory is used to describe the communication network topologies among CAVs. Subsequently, the feedback-based protocol is proposed to control the vehicular platoon. In addition, the stability and consensus of the proposed protocol are analyzed using the Lyapunov technique and the LaSalle’s invariance principle. Effects of different communication network topologies on convergence and robustness of platoon control are investigated. Results from numerical experiments demonstrate the effectiveness of the proposed protocol with respect to the position and velocity consensus in terms of the convergence time and robustness.</div>
        <div className="ThesisClassic-keyWord-title">Keyword</div>
        <div className="ThesisClassic-keyWord">Connected autonomous vehicle; Platoon control; Communication network topologies; Consensus</div>
        <div className="ThesisClassic-publication-title">Article</div>
        <div className="ThesisClassic-publication">Chinese Control Conference</div>
        <div className="ThesisClassic-date-title">Data</div>
        <div className="ThesisClassic-date">July 27-29, 2016</div>
      </div>
    </div>

  )
}

